config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  devise_for :users
  resources :cities do
    resources :posts
     end

  root 'home#index'
  get 'users/show'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :city
  belongs_to :user
  validates :tip, presence: true
  validates :title, length: {in: 1..200}

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource only: [:edit, :update, :destroy]

  def index
    @post = Post.all
  end

  def new
    @city = City.friendly.find params[:city_id]
    @post = Post.new
  end
  
  def create
    @city = City.friendly.find params[:city_id]
    @post = @city.posts.new(post_params)

    # validation error message
    if @post.valid?
      @post.save
      redirect_to city_post_path(@city, @post)
    else 
      flash.alert = "Your post must have a title between 1-200 characters & you must include a tip."
      redirect_to new_city_post_path
    end

  end

  def show
    @post = Post.find params[:id]
  end

  def edit
    @city = City.friendly.find params[:city_id]
    @post = Post.find params[:id]
  end

  def update
    @city = City.friendly.find params[:city_id] 
    @post = @city.posts.find params[:id]
    @post.update(post_params)
    
    redirect_to city_post_path(@city)
  end

  def destroy
    @city = City.friendly.find params[:city_id]
    @post = @city.posts.find params[:id]
    @post.destroy

    redirect_to city_path(@city)
  end

  rescue_from CanCan::AccessDenied do |exception|
    @city = City.friendly.find params[:city_id]
    flash[:notice] = "Access denied! This isn't your post."
    flash.keep(:notice)

    redirect_to city_post_path(@city)

  end

  private
  def post_params
      post = params.require(:post).permit(:title, :tip, :post_id, :user_id)
      user_id = {user_id: current_user.id}
      post.merge(user_id)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div>
    <div class="container-post-views">
         <div class="form-group"> 

        <h3>Edit Post</h3>
<%# alert for edit posts  %>
        <%= render "partials/form" %>
        <% if flash.alert %>
          <div><%=flash.alert%></div>
        <%end%> 
        <p class="notice"><%= notice %></p>
    </div>
    </div>
</div>

app/views/posts/new.html.erb
<div>
    <div class="container-post-views">
         <div class="form-group"> 

        <h3>Create a New Post</h3>
<%# alert for new posts  %>
        <%= render "partials/form" %>
        <% if flash.alert %>
          <div><%=flash.alert%></div>
        <%end%> 
        <p class="notice"><%= notice %></p>
    </div>
</div>
</div>

app/views/posts/show.html.erb
<div>
    <div class="container-post-views"> 
        <div class="details">
            <h3><%= @post.title %></h3>
            <p><%= @post.tip %></p>
        </div>

        <div>
            <div class="edit-button">
                <% if can? :update, @post %>
                <button class="btn"> <%= link_to  "edit tip", edit_city_post_path %> </button>
                <% end %> 
                &nbsp;
                &nbsp;
                &nbsp;
                <button class="btn"> <%= link_to  "back to city", city_path(@post.city, @post) %> </button>
            </div>
            <div class="delete-button">
            <% if can? :destroy, @post %>
            <%= form_for [@post.city, @post], method: :delete do |f| %> 
            <%= f.submit "Delete", class: "delete btn", data: {confirm: "Are you sure?"} %>
            <% end %>
            <% end %> 
            </div>
        </div>
    </div>
</div>