config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  devise_for :users
  resources :cities do
    resources :posts
     end

  root 'home#index'
  get 'users/show'
end

app/models/city.rb
class City < ApplicationRecord
    extend FriendlyId
    # added friendly to make browser show city name
    friendly_id :name, use: :slugged
    
    has_many :posts, dependent: :destroy
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def new
    @city = City.new
  end
  
  def create
    @city = City.create!(city_params)
    redirect_to cities_path
  end

  def show
    @city = City.friendly.find(params[:id])
  end

  def edit
    @city = City.friendly.find(params[:id])
  end

  def update
    @city = City.friendly.find(params[:id])
    @city.update(city_params)

    redirect_to cities_path(@city)
  end

  def destroy
    @city = City.friendly.find(params[:id])
    @city.destroy

    redirect_to cities_path
  end

  private
  def city_params
  params.require(:city).permit(:name, :description, :image)
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/edit.html.erb
<div>
  <div class="container-all-views">
    <h1>Edit City</h1>

    <div class="form-group">
    <%= form_for @city do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class:"form-control" %> </br>

      <%= f.label :description %>
      <%= f.text_area :description, class:"form-control" %> </br>

      <%= f.label :image %>
      <%= f.text_field :image, class:"form-control" %> </br>

      <%= f.submit class: "btn-form" %>

    <% end %>
    </div>
  </div>
</div>

app/views/cities/index.html.erb
<div>
        <% @cities.order("created_at ASC").each do |city| %>
            <h1 class="inlinkname"><%= link_to city.name, city_path(city) %></h1>
            <div class="flex-container"><%= image_tag(city.image, alt: "Atlanta", class: "indeximg")%></div>
        <% end %>
</div>

app/views/cities/new.html.erb
<div>
  <div class="container-all-views">
    <h1>Create a New City</h1>

    <div class="form-group">
    <%= form_for @city do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class:"form-control" %> </br>

      <%= f.label :description %>
      <%= f.text_area :description, class:"form-control" %></br>

      <%= f.label :image %>
      <%= f.text_field :image, class:"form-control" %></br>

      <%= f.submit class: "btn-lrg"%>

    <% end %>
    </div>
  </div>
</div>

app/views/cities/show.html.erb
<div>
  <div class="container-city-views">
    <%= image_tag @city.image, class:"img"%>
    <p class="city-header"><%= @city.name %></p>
  <div>
    <div class="city-details">
    <p class="city"><%= @city.description %></p>
    <div>
      <div class="new-tip">Have a great tip about this city? <%= link_to  "Add a new tip here.", new_city_post_path(@city.slug) %></div>
    </div>
    <div class="posts">
    <%# post index page  %>
          <% @city.posts.order("created_at DESC").each do |post| %>
            <%= link_to post.title, city_post_path(@city.slug, post.id) %>
            <p><%=truncate(post.tip, length: 100)%> <%=link_to " >>", city_post_path(@city.slug, post)%></p>
            <p><%= distance_of_time_in_words(post.created_at, Time.now)%> ago</p><br/>
          <% end %>
    </div>
  </div>
  </div>
</div>


 



 